# coding: utf-8

"""
    Samsara API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2020-06-15
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import samsara
from samsara.models.vehicle_stats_gps import VehicleStatsGps  # noqa: E501
from samsara.rest import ApiException

class TestVehicleStatsGps(unittest.TestCase):
    """VehicleStatsGps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test VehicleStatsGps
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = samsara.models.vehicle_stats_gps.VehicleStatsGps()  # noqa: E501
        if include_optional :
            return VehicleStatsGps(
                heading_degrees = 120, 
                latitude = 122.142, 
                longitude = -93.343, 
                reverse_geo = samsara.models.vehicle_location_reverse_geo.VehicleLocationReverseGeo(
                    formatted_location = '16 N Fair Oaks Ave, Pasadena, CA 91103', ), 
                speed_miles_per_hour = 48.3, 
                time = '2020-01-27T07:06:25Z'
            )
        else :
            return VehicleStatsGps(
                latitude = 122.142,
                longitude = -93.343,
                time = '2020-01-27T07:06:25Z',
        )

    def testVehicleStatsGps(self):
        """Test VehicleStatsGps"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
