# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

from .types import (
    FuelPurchasePostFuelPurchaseRequestBodyFuelGrade,
    FuelPurchasePostFuelPurchaseRequestBodyIftaFuelType,
    GetFuelEnergyVehicleReportsRequestEnergyType,
)

__all__ = [
    "FuelPurchasePostFuelPurchaseRequestBodyFuelGrade",
    "FuelPurchasePostFuelPurchaseRequestBodyIftaFuelType",
    "GetFuelEnergyVehicleReportsRequestEnergyType",
]
