# This file was auto-generated by Fern from our API Definition.

import typing

WorkOrderObjectResponseBodyCategory = typing.Union[
    typing.Literal["Annual", "Corrective", "Damage Repair", "Preventive", "Recall", "Unspecified"], typing.Any
]
