# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        DeviceRecoveryRecoverAssetRequestBodyMissingReason,
        DeviceRecoveryRecoverAssetRequestBodyRecoveryStatus,
        DeviceRecoveryRecoverAssetRequestBodyStatus,
        FunctionsStartFunctionRunRequestBodyParamsOverride,
        GetAssetsInputsRequestType,
        GetDriverEfficiencyRequestDriverActivationStatus,
        GetHosEldEventsRequestDriverActivationStatus,
        GetJobsRequestStatus,
        GetQualificationRecordsStreamRequestEntityType,
        GetQualificationTypesRequestEntityType,
        ListDriverWorkflowsRequestWorkflowType,
        PlacesPatchPlaceRequestBodyCameraRecordingModeType,
        PlacesPatchPlaceRequestBodyExternalIds,
        PlacesPostPlaceRequestBodyCameraRecordingModeType,
        PlacesPostPlaceRequestBodyExternalIds,
        RidershipPassengersCreateRidershipPassengerRequestBodyClassification,
        RidershipPassengersUpdateRidershipPassengerRequestBodyClassification,
        SafetyEventsV2PatchSafetyEventsV2BatchRequestBodyBehaviorLabelsToAddItem,
        SafetyEventsV2PatchSafetyEventsV2BatchRequestBodyBehaviorLabelsToRemoveItem,
        SafetyEventsV2PatchSafetyEventsV2BatchRequestBodyContextLabelsToAddItem,
        SafetyEventsV2PatchSafetyEventsV2BatchRequestBodyContextLabelsToRemoveItem,
        SafetyEventsV2PatchSafetyEventsV2BatchRequestBodyEventState,
        TachographFileUploadsPostTachographFileUploadRequestBodyContentType,
        TachographFileUploadsPostTachographFileUploadRequestBodyFileType,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "DeviceRecoveryRecoverAssetRequestBodyMissingReason": ".types",
    "DeviceRecoveryRecoverAssetRequestBodyRecoveryStatus": ".types",
    "DeviceRecoveryRecoverAssetRequestBodyStatus": ".types",
    "FunctionsStartFunctionRunRequestBodyParamsOverride": ".types",
    "GetAssetsInputsRequestType": ".types",
    "GetDriverEfficiencyRequestDriverActivationStatus": ".types",
    "GetHosEldEventsRequestDriverActivationStatus": ".types",
    "GetJobsRequestStatus": ".types",
    "GetQualificationRecordsStreamRequestEntityType": ".types",
    "GetQualificationTypesRequestEntityType": ".types",
    "ListDriverWorkflowsRequestWorkflowType": ".types",
    "PlacesPatchPlaceRequestBodyCameraRecordingModeType": ".types",
    "PlacesPatchPlaceRequestBodyExternalIds": ".types",
    "PlacesPostPlaceRequestBodyCameraRecordingModeType": ".types",
    "PlacesPostPlaceRequestBodyExternalIds": ".types",
    "RidershipPassengersCreateRidershipPassengerRequestBodyClassification": ".types",
    "RidershipPassengersUpdateRidershipPassengerRequestBodyClassification": ".types",
    "SafetyEventsV2PatchSafetyEventsV2BatchRequestBodyBehaviorLabelsToAddItem": ".types",
    "SafetyEventsV2PatchSafetyEventsV2BatchRequestBodyBehaviorLabelsToRemoveItem": ".types",
    "SafetyEventsV2PatchSafetyEventsV2BatchRequestBodyContextLabelsToAddItem": ".types",
    "SafetyEventsV2PatchSafetyEventsV2BatchRequestBodyContextLabelsToRemoveItem": ".types",
    "SafetyEventsV2PatchSafetyEventsV2BatchRequestBodyEventState": ".types",
    "TachographFileUploadsPostTachographFileUploadRequestBodyContentType": ".types",
    "TachographFileUploadsPostTachographFileUploadRequestBodyFileType": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "DeviceRecoveryRecoverAssetRequestBodyMissingReason",
    "DeviceRecoveryRecoverAssetRequestBodyRecoveryStatus",
    "DeviceRecoveryRecoverAssetRequestBodyStatus",
    "FunctionsStartFunctionRunRequestBodyParamsOverride",
    "GetAssetsInputsRequestType",
    "GetDriverEfficiencyRequestDriverActivationStatus",
    "GetHosEldEventsRequestDriverActivationStatus",
    "GetJobsRequestStatus",
    "GetQualificationRecordsStreamRequestEntityType",
    "GetQualificationTypesRequestEntityType",
    "ListDriverWorkflowsRequestWorkflowType",
    "PlacesPatchPlaceRequestBodyCameraRecordingModeType",
    "PlacesPatchPlaceRequestBodyExternalIds",
    "PlacesPostPlaceRequestBodyCameraRecordingModeType",
    "PlacesPostPlaceRequestBodyExternalIds",
    "RidershipPassengersCreateRidershipPassengerRequestBodyClassification",
    "RidershipPassengersUpdateRidershipPassengerRequestBodyClassification",
    "SafetyEventsV2PatchSafetyEventsV2BatchRequestBodyBehaviorLabelsToAddItem",
    "SafetyEventsV2PatchSafetyEventsV2BatchRequestBodyBehaviorLabelsToRemoveItem",
    "SafetyEventsV2PatchSafetyEventsV2BatchRequestBodyContextLabelsToAddItem",
    "SafetyEventsV2PatchSafetyEventsV2BatchRequestBodyContextLabelsToRemoveItem",
    "SafetyEventsV2PatchSafetyEventsV2BatchRequestBodyEventState",
    "TachographFileUploadsPostTachographFileUploadRequestBodyContentType",
    "TachographFileUploadsPostTachographFileUploadRequestBodyFileType",
]
