# coding: utf-8

"""
    Samsara API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2020-06-15
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from samsara.configuration import Configuration


class HosCycle(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cycle_remaining_duration_ms': 'float',
        'cycle_started_at_time': 'str',
        'cycle_tomorrow_duration_ms': 'float'
    }

    attribute_map = {
        'cycle_remaining_duration_ms': 'cycleRemainingDurationMs',
        'cycle_started_at_time': 'cycleStartedAtTime',
        'cycle_tomorrow_duration_ms': 'cycleTomorrowDurationMs'
    }

    def __init__(self, cycle_remaining_duration_ms=None, cycle_started_at_time=None, cycle_tomorrow_duration_ms=None, local_vars_configuration=None):  # noqa: E501
        """HosCycle - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._cycle_remaining_duration_ms = None
        self._cycle_started_at_time = None
        self._cycle_tomorrow_duration_ms = None
        self.discriminator = None

        if cycle_remaining_duration_ms is not None:
            self.cycle_remaining_duration_ms = cycle_remaining_duration_ms
        if cycle_started_at_time is not None:
            self.cycle_started_at_time = cycle_started_at_time
        if cycle_tomorrow_duration_ms is not None:
            self.cycle_tomorrow_duration_ms = cycle_tomorrow_duration_ms

    @property
    def cycle_remaining_duration_ms(self):
        """Gets the cycle_remaining_duration_ms of this HosCycle.  # noqa: E501

        Remaining on duty or driving time the driver has in the current cycle in milliseconds. For property-carrying drivers, this is the amount of time the driver can be on duty or driving before hitting the 60/70-hour limit in 7/8 days.  # noqa: E501

        :return: The cycle_remaining_duration_ms of this HosCycle.  # noqa: E501
        :rtype: float
        """
        return self._cycle_remaining_duration_ms

    @cycle_remaining_duration_ms.setter
    def cycle_remaining_duration_ms(self, cycle_remaining_duration_ms):
        """Sets the cycle_remaining_duration_ms of this HosCycle.

        Remaining on duty or driving time the driver has in the current cycle in milliseconds. For property-carrying drivers, this is the amount of time the driver can be on duty or driving before hitting the 60/70-hour limit in 7/8 days.  # noqa: E501

        :param cycle_remaining_duration_ms: The cycle_remaining_duration_ms of this HosCycle.  # noqa: E501
        :type: float
        """

        self._cycle_remaining_duration_ms = cycle_remaining_duration_ms

    @property
    def cycle_started_at_time(self):
        """Gets the cycle_started_at_time of this HosCycle.  # noqa: E501

        UTC timestamp in RFC 3339 format. Example: `2020-01-27T07:06:25Z`.  # noqa: E501

        :return: The cycle_started_at_time of this HosCycle.  # noqa: E501
        :rtype: str
        """
        return self._cycle_started_at_time

    @cycle_started_at_time.setter
    def cycle_started_at_time(self, cycle_started_at_time):
        """Sets the cycle_started_at_time of this HosCycle.

        UTC timestamp in RFC 3339 format. Example: `2020-01-27T07:06:25Z`.  # noqa: E501

        :param cycle_started_at_time: The cycle_started_at_time of this HosCycle.  # noqa: E501
        :type: str
        """

        self._cycle_started_at_time = cycle_started_at_time

    @property
    def cycle_tomorrow_duration_ms(self):
        """Gets the cycle_tomorrow_duration_ms of this HosCycle.  # noqa: E501

        Remaining on duty or driving time the driver has available tomorrow in milliseconds. For property-carrying drivers this is calculated based on the 60/70-hour limit in 7/8 days rule.  # noqa: E501

        :return: The cycle_tomorrow_duration_ms of this HosCycle.  # noqa: E501
        :rtype: float
        """
        return self._cycle_tomorrow_duration_ms

    @cycle_tomorrow_duration_ms.setter
    def cycle_tomorrow_duration_ms(self, cycle_tomorrow_duration_ms):
        """Sets the cycle_tomorrow_duration_ms of this HosCycle.

        Remaining on duty or driving time the driver has available tomorrow in milliseconds. For property-carrying drivers this is calculated based on the 60/70-hour limit in 7/8 days rule.  # noqa: E501

        :param cycle_tomorrow_duration_ms: The cycle_tomorrow_duration_ms of this HosCycle.  # noqa: E501
        :type: float
        """

        self._cycle_tomorrow_duration_ms = cycle_tomorrow_duration_ms

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HosCycle):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HosCycle):
            return True

        return self.to_dict() != other.to_dict()
