# This file was auto-generated by Fern from our API Definition.

import typing

AssetsUpdateAssetRequestBodyRegulationMode = typing.Union[
    typing.Literal["mixed", "regulated", "unregulated"], typing.Any
]
