# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .alert_object_workforce_camera_device_response_body import AlertObjectWorkforceCameraDeviceResponseBody
from .goa_tag_tiny_response_response_body import GoaTagTinyResponseResponseBody


class AlertObjectOnvifCameraStreamResponseBody(UniversalBaseModel):
    """
    A camera stream associated with the alert.
    """

    camera_device: typing_extensions.Annotated[
        typing.Optional[AlertObjectWorkforceCameraDeviceResponseBody], FieldMetadata(alias="cameraDevice")
    ] = None
    id: str = pydantic.Field()
    """
    The ID of the camera stream associated with the alert.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the camera stream.
    """

    tags: typing.Optional[typing.List[GoaTagTinyResponseResponseBody]] = pydantic.Field(default=None)
    """
    The list of [tags](https://kb.samsara.com/hc/en-us/articles/360026674631-Using-Tags-and-Tag-Nesting) associated with the camera stream.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
