# This file was auto-generated by Fern from our API Definition.

import typing

FleetOrderTaskObjectResponseBodyTaskType = typing.Union[
    typing.Literal["unknown", "delivery", "pickup", "pickupDelivery"], typing.Any
]
