# This file was auto-generated by Fern from our API Definition.

import typing

HealthResponseResponseBodyPrimaryHealthReason = typing.Union[
    typing.Literal[
        "assetUnplugged",
        "cameraMisaligned",
        "dataPending",
        "healthy",
        "inwardCameraObstruction",
        "irregularRecording",
        "lowConnectivity",
        "lowDeviceBattery",
        "lowUptime",
        "mediaInputLowConnectivity",
        "missingEldDiagnostics",
        "missingVin",
        "needsAttribute",
        "needsReplacement",
        "newlyInstalledDevice",
        "noGpsSignal",
        "notDetected",
        "outwardCameraObstruction",
        "recordingTimeRequired",
        "unknown",
        "unstablePower",
        "vgUnplugged",
    ],
    typing.Any,
]
