# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .hub_route_template_depot_object_response_body import HubRouteTemplateDepotObjectResponseBody
from .hub_route_template_location_object_response_body import HubRouteTemplateLocationObjectResponseBody


class HubRouteTemplateObjectResponseBody(UniversalBaseModel):
    """
    A route template for a hub.
    """

    created_at_time: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAtTime"),
        pydantic.Field(
            alias="createdAtTime", description="The timestamp when the route template was created, in RFC 3339 format."
        ),
    ]
    default_depot_end: typing_extensions.Annotated[
        typing.Optional[HubRouteTemplateDepotObjectResponseBody],
        FieldMetadata(alias="defaultDepotEnd"),
        pydantic.Field(alias="defaultDepotEnd"),
    ] = None
    default_depot_start: typing_extensions.Annotated[
        typing.Optional[HubRouteTemplateDepotObjectResponseBody],
        FieldMetadata(alias="defaultDepotStart"),
        pydantic.Field(alias="defaultDepotStart"),
    ] = None
    distance_meters: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="distanceMeters"),
        pydantic.Field(alias="distanceMeters", description="Total distance of the route in meters."),
    ]
    duration_seconds: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="durationSeconds"),
        pydantic.Field(alias="durationSeconds", description="Total duration of the route in seconds."),
    ]
    earliest_start_time: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="earliestStartTime"),
        pydantic.Field(
            alias="earliestStartTime",
            description="Default start time of day for the route template, in HH:MM format in the hub's local timezone (e.g. '08:00').",
        ),
    ] = None
    hub_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="hubId"),
        pydantic.Field(alias="hubId", description="The hub identifier this route template belongs to."),
    ]
    hub_timezone: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="hubTimezone"),
        pydantic.Field(alias="hubTimezone", description="The IANA timezone of the hub (e.g. 'America/Los_Angeles')."),
    ]
    id: str = pydantic.Field()
    """
    The unique identifier for the route template.
    """

    locations: typing.List[HubRouteTemplateLocationObjectResponseBody] = pydantic.Field()
    """
    Ordered list of stop locations in the route template.
    """

    name: str = pydantic.Field()
    """
    The name of the route template.
    """

    updated_at_time: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="updatedAtTime"),
        pydantic.Field(
            alias="updatedAtTime",
            description="The timestamp when the route template was last updated, in RFC 3339 format.",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
