# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .entity_list_purchase_orders_part_definition_ref_type_response_body import (
    EntityListPurchaseOrdersPartDefinitionRefTypeResponseBody,
)
from .entity_list_purchase_orders_vendor_ref_type_response_body import EntityListPurchaseOrdersVendorRefTypeResponseBody
from .list_purchase_orders_entity_purchase_order_core_recoverability_policy_type_response_body import (
    ListPurchaseOrdersEntityPurchaseOrderCoreRecoverabilityPolicyTypeResponseBody,
)
from .list_purchase_orders_entity_purchase_order_money_type_response_body import (
    ListPurchaseOrdersEntityPurchaseOrderMoneyTypeResponseBody,
)
from .list_purchase_orders_entity_purchase_order_purchase_order_core_charge_type_response_body_core_charge_status import (
    ListPurchaseOrdersEntityPurchaseOrderPurchaseOrderCoreChargeTypeResponseBodyCoreChargeStatus,
)


class ListPurchaseOrdersEntityPurchaseOrderPurchaseOrderCoreChargeTypeResponseBody(UniversalBaseModel):
    """
    ListPurchaseOrdersEntityPurchaseOrderPurchaseOrderCoreCharge object
    """

    core_charge_status: typing_extensions.Annotated[
        typing.Optional[ListPurchaseOrdersEntityPurchaseOrderPurchaseOrderCoreChargeTypeResponseBodyCoreChargeStatus],
        FieldMetadata(alias="coreChargeStatus"),
        pydantic.Field(
            alias="coreChargeStatus",
            description="Whether the core charge is active or removed or disabled.  Valid values: `Unknown`, `Active`, `RemovedOrDisabled`",
        ),
    ] = None
    core_part_samsara: typing_extensions.Annotated[
        typing.Optional[EntityListPurchaseOrdersPartDefinitionRefTypeResponseBody],
        FieldMetadata(alias="corePartSamsara"),
        pydantic.Field(alias="corePartSamsara"),
    ] = None
    recoverability_policy: typing_extensions.Annotated[
        typing.Optional[ListPurchaseOrdersEntityPurchaseOrderCoreRecoverabilityPolicyTypeResponseBody],
        FieldMetadata(alias="recoverabilityPolicy"),
        pydantic.Field(alias="recoverabilityPolicy"),
    ] = None
    return_recipient_vendor: typing_extensions.Annotated[
        typing.Optional[EntityListPurchaseOrdersVendorRefTypeResponseBody],
        FieldMetadata(alias="returnRecipientVendor"),
        pydantic.Field(alias="returnRecipientVendor"),
    ] = None
    unit_core_amount: typing_extensions.Annotated[
        typing.Optional[ListPurchaseOrdersEntityPurchaseOrderMoneyTypeResponseBody],
        FieldMetadata(alias="unitCoreAmount"),
        pydantic.Field(alias="unitCoreAmount"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
