# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .entity_list_purchase_orders_part_definition_ref_type_response_body import (
    EntityListPurchaseOrdersPartDefinitionRefTypeResponseBody,
)
from .entity_list_purchase_orders_place_ref_type_response_body import EntityListPurchaseOrdersPlaceRefTypeResponseBody
from .list_purchase_orders_entity_purchase_order_money_type_response_body import (
    ListPurchaseOrdersEntityPurchaseOrderMoneyTypeResponseBody,
)
from .list_purchase_orders_entity_purchase_order_purchase_order_core_charge_type_response_body import (
    ListPurchaseOrdersEntityPurchaseOrderPurchaseOrderCoreChargeTypeResponseBody,
)
from .list_purchase_orders_entity_purchase_order_purchase_order_part_type_response_body_unit_of_measure_type import (
    ListPurchaseOrdersEntityPurchaseOrderPurchaseOrderPartTypeResponseBodyUnitOfMeasureType,
)
from .list_purchase_orders_entity_purchase_order_tax_adjustment_type_response_body import (
    ListPurchaseOrdersEntityPurchaseOrderTaxAdjustmentTypeResponseBody,
)


class ListPurchaseOrdersEntityPurchaseOrderPurchaseOrderPartTypeResponseBody(UniversalBaseModel):
    """
    ListPurchaseOrdersEntityPurchaseOrderPurchaseOrderPart object
    """

    batch_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="batchNumber"),
        pydantic.Field(alias="batchNumber", description="Batch or lot number for the ordered part."),
    ] = None
    core_charge: typing_extensions.Annotated[
        typing.Optional[ListPurchaseOrdersEntityPurchaseOrderPurchaseOrderCoreChargeTypeResponseBody],
        FieldMetadata(alias="coreCharge"),
        pydantic.Field(alias="coreCharge"),
    ] = None
    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Description of the ordered part.
    """

    line_item_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="lineItemId"),
        pydantic.Field(alias="lineItemId", description="Stable identifier for the purchase order line."),
    ] = None
    part_samsara: typing_extensions.Annotated[
        typing.Optional[EntityListPurchaseOrdersPartDefinitionRefTypeResponseBody],
        FieldMetadata(alias="partSamsara"),
        pydantic.Field(alias="partSamsara"),
    ] = None
    place: typing.Optional[EntityListPurchaseOrdersPlaceRefTypeResponseBody] = None
    quantity_ordered: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="quantityOrdered"),
        pydantic.Field(alias="quantityOrdered", description="Quantity ordered on this line."),
    ] = None
    quantity_received: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="quantityReceived"),
        pydantic.Field(alias="quantityReceived", description="Quantity received on this line."),
    ] = None
    tax: typing.Optional[ListPurchaseOrdersEntityPurchaseOrderTaxAdjustmentTypeResponseBody] = None
    unit_cost: typing_extensions.Annotated[
        typing.Optional[ListPurchaseOrdersEntityPurchaseOrderMoneyTypeResponseBody],
        FieldMetadata(alias="unitCost"),
        pydantic.Field(alias="unitCost"),
    ] = None
    unit_of_measure_type: typing_extensions.Annotated[
        typing.Optional[ListPurchaseOrdersEntityPurchaseOrderPurchaseOrderPartTypeResponseBodyUnitOfMeasureType],
        FieldMetadata(alias="unitOfMeasureType"),
        pydantic.Field(
            alias="unitOfMeasureType",
            description="Unit of measure for quantities on this line.  Valid values: `Unknown`, `Each`, `Set`, `Pack`, `Box`, `Pound`, `Kilogram`, `Ounce`, `Liter`, `Milliliter`, `Gallon`, `Quart`, `FluidOunce`, `Inch`, `Foot`, `Meter`, `Yard`, `SquareFoot`, `SquareMeter`, `Pint`, `Hundred`, `Roll`",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
