# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .list_issues_entity_ground_intelligence_issue_lat_lng_type_response_body import (
    ListIssuesEntityGroundIntelligenceIssueLatLngTypeResponseBody,
)


class ListIssuesEntityGroundIntelligenceIssueGroundIntelligenceIssueLocationTypeResponseBody(UniversalBaseModel):
    """
    ListIssuesEntityGroundIntelligenceIssueGroundIntelligenceIssueLocation object
    """

    point: typing.Optional[ListIssuesEntityGroundIntelligenceIssueLatLngTypeResponseBody] = None
    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Shape of the issue location.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
