# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PatchPlaceHubLocationUpsertBodyRequestBody(UniversalBaseModel):
    """
    Hub location upsert entry for PATCH /places.
    """

    display_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="displayName"),
        pydantic.Field(
            alias="displayName", description="Optional label; stored as planner-facing notes for this hub row."
        ),
    ] = None
    external_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="externalId"),
        pydantic.Field(alias="externalId", description="External identifier for this hub row."),
    ] = None
    hub_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="hubId"), pydantic.Field(alias="hubId", description="Planner hub UUID for this row.")
    ]
    hub_location_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="hubLocationId"),
        pydantic.Field(alias="hubLocationId", description="Existing hub location UUID; omit to create a new row."),
    ] = None
    is_depot: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isDepot"),
        pydantic.Field(alias="isDepot", description="Whether this hub location is a depot."),
    ] = None
    is_ignore_order_service_time_enabled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isIgnoreOrderServiceTimeEnabled"),
        pydantic.Field(
            alias="isIgnoreOrderServiceTimeEnabled",
            description="Whether order service time is ignored at this location.",
        ),
    ] = None
    location_position_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="locationPositionType"),
        pydantic.Field(
            alias="locationPositionType", description="Stop position preference: unspecified, any, first, or last."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
