# This file was auto-generated by Fern from our API Definition.

import typing

PreferredStationPriceInputRequestBodyVolumeUnit = typing.Union[
    typing.Literal["liter", "gallon", "imperialGallon"], typing.Any
]
