# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .notification_recipient_response_response_body import NotificationRecipientResponseResponseBody
from .recovery_photo_response_body import RecoveryPhotoResponseBody
from .recovery_state_response_body_update_source import RecoveryStateResponseBodyUpdateSource


class RecoveryStateResponseBody(UniversalBaseModel):
    """
    A recovered asset with its recovery details, including recovery photos.
    """

    id: str = pydantic.Field()
    """
    The unique Samsara ID of the asset.
    """

    name: str = pydantic.Field()
    """
    The human-readable name of the asset.
    """

    note: typing.Optional[str] = pydantic.Field(default=None)
    """
    A note associated with the recovery.
    """

    notification_recipients: typing.Optional[typing.List[NotificationRecipientResponseResponseBody]] = pydantic.Field(
        default=None
    )
    """
    Users subscribed to location update notifications for this asset.
    """

    recovery_photos: typing.Optional[typing.List[RecoveryPhotoResponseBody]] = pydantic.Field(default=None)
    """
    Photos associated with the recovery event. URLs are temporary and expire at url_expires_at_ms.
    """

    update_source: typing.Optional[RecoveryStateResponseBodyUpdateSource] = pydantic.Field(default=None)
    """
    The source of the last update to this recovery state. Defaults to `dashboard` if not explicitly set.  Valid values: `dashboard`, `api`
    """

    updated_at_ms: int = pydantic.Field()
    """
    Timestamp when the recovery state was last updated, in milliseconds since epoch.
    """

    updated_by_user_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    The ID of the user who last updated the recovery state.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
