# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ResolveAssignmentByDetailsResponseBodyResponseBody(UniversalBaseModel):
    """
    Response body containing the resolved driver information.
    """

    driver_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="driverId"),
        pydantic.Field(alias="driverId", description="The resolved Samsara driver ID."),
    ]
    driver_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="driverName"),
        pydantic.Field(alias="driverName", description="The matched driver name."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
