# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .fleet_order_customer_property_object_request_body import FleetOrderCustomerPropertyObjectRequestBody
from .fleet_order_task_upsert_input_request_body import FleetOrderTaskUpsertInputRequestBody
from .route_stop_order_upsert_input_request_body_external_ids import RouteStopOrderUpsertInputRequestBodyExternalIds


class RouteStopOrderUpsertInputRequestBody(UniversalBaseModel):
    """
    A canonical order to upsert and attach to the containing route stop.
    """

    customer_properties: typing_extensions.Annotated[
        typing.Optional[typing.List[FleetOrderCustomerPropertyObjectRequestBody]],
        FieldMetadata(alias="customerProperties"),
        pydantic.Field(alias="customerProperties", description="Order-specific customer metadata."),
    ] = None
    external_ids: typing_extensions.Annotated[
        typing.Optional[RouteStopOrderUpsertInputRequestBodyExternalIds],
        FieldMetadata(alias="externalIds"),
        pydantic.Field(alias="externalIds", description="Org-scoped external identifiers."),
    ] = None
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Existing Samsara order UUID. Required unless externalIds is supplied.
    """

    samsara_customer_order_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="samsaraCustomerOrderName"),
        pydantic.Field(alias="samsaraCustomerOrderName", description="Human-readable order label."),
    ] = None
    tasks: typing.List[FleetOrderTaskUpsertInputRequestBody] = pydantic.Field()
    """
    Tasks to upsert and attach to the containing stop.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
