# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UpdateVendorEntityVendorVendorHourlyMoneyTypeResponseBody(UniversalBaseModel):
    """
    VendorHourlyMoney object
    """

    amount: typing.Optional[str] = pydantic.Field(default=None)
    """
    Nonnegative decimal hourly amount in the organization's currency.
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO 4217 currency matching the organization's current currency.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
