# This file was auto-generated by Fern from our API Definition.

import typing

UpdatePurchaseOrderEntityPurchaseOrderPurchaseOrderCoreChargeInputTypeRequestBodyCoreChargeStatus = typing.Union[
    typing.Literal["Unknown", "Active", "RemovedOrDisabled"], typing.Any
]
