# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class V1VehicleMaintenancePassengerDiagnosticTroubleCodes(UniversalBaseModel):
    dtc_description: typing_extensions.Annotated[
        str, FieldMetadata(alias="dtcDescription"), pydantic.Field(alias="dtcDescription")
    ]
    dtc_id: typing_extensions.Annotated[int, FieldMetadata(alias="dtcId"), pydantic.Field(alias="dtcId")]
    dtc_short_code: typing_extensions.Annotated[
        str, FieldMetadata(alias="dtcShortCode"), pydantic.Field(alias="dtcShortCode")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
