# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .v_1_temperature_response_sensors import V1TemperatureResponseSensors


class V1TemperatureResponse(UniversalBaseModel):
    """
    Contains the current temperatures of a sensor.
    """

    group_id: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="groupId")] = pydantic.Field(
        default=None
    )
    """
    Deprecated.
    """

    sensors: typing.Optional[typing.List[V1TemperatureResponseSensors]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
