# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .time import Time
from .vehicle_stats_seatbelt_driver_value import VehicleStatsSeatbeltDriverValue


class VehicleStatsSeatbeltDriver(UniversalBaseModel):
    """
    Seatbelt Driver Status as read from the vehicle. `Buckled` or `Unbuckled`.
    """

    time: Time
    value: VehicleStatsSeatbeltDriverValue = pydantic.Field()
    """
    Seatbelt Driver Status as read from the vehicle. `Buckled` or `Unbuckled`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
