# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .vehicle_location_response_body_odometer_type import VehicleLocationResponseBodyOdometerType


class VehicleLocationResponseBody(UniversalBaseModel):
    """
    Contains the location, in latitude and longitude, of a vehicle.
    """

    driver_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="driverId"),
        pydantic.Field(alias="driverId", description="The ID of the driver currently assigned to this vehicle."),
    ] = None
    heading: typing.Optional[float] = pydantic.Field(default=None)
    """
    Heading in degrees.
    """

    id: int = pydantic.Field()
    """
    ID of the vehicle.
    """

    latitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    Latitude in decimal degrees.
    """

    location: typing.Optional[str] = pydantic.Field(default=None)
    """
    Text representation of nearest identifiable location to (latitude, longitude) coordinates.
    """

    longitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    Longitude in decimal degrees.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the vehicle.
    """

    odometer_meters: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="odometerMeters"),
        pydantic.Field(alias="odometerMeters", description="The number of meters reported by the odometer."),
    ] = None
    odometer_type: typing_extensions.Annotated[
        typing.Optional[VehicleLocationResponseBodyOdometerType],
        FieldMetadata(alias="odometerType"),
        pydantic.Field(
            alias="odometerType",
            description="The source of data for odometerMeters. Will be either GPS or OBD  Valid values: `GPS`, `OBD`",
        ),
    ] = None
    on_trip: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="onTrip"),
        pydantic.Field(
            alias="onTrip",
            description="Whether or not a trip is currently in progress for this vehicle. More information available via /fleet/trips endpoint.",
        ),
    ] = None
    route_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[int]],
        FieldMetadata(alias="routeIds"),
        pydantic.Field(alias="routeIds", description="A list of currently active route IDs that the vehicle is in."),
    ] = None
    speed: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speed in miles per hour.
    """

    time: typing.Optional[int] = pydantic.Field(default=None)
    """
    The time the reported location was logged, reported as a UNIX timestamp in milliseconds.
    """

    vin: typing.Optional[str] = pydantic.Field(default=None)
    """
    Vehicle Identification Number (VIN) of the vehicle.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
