# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .time import Time
from .vehicle_stats_spreader_active_value import VehicleStatsSpreaderActiveValue


class VehicleStatsSpreaderActive(UniversalBaseModel):
    """
    Whether vehicle is actively spreading any material.
    """

    time: Time
    value: VehicleStatsSpreaderActiveValue = pydantic.Field()
    """
    Whether vehicle is actively spreading any material.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
