# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.entity_preventative_maintenance_schedules_service_list_preventive_maintenance_schedules_response_body import (
    EntityPreventativeMaintenanceSchedulesServiceListPreventiveMaintenanceSchedulesResponseBody,
)
from ..types.entity_upcoming_preventative_maintenances_service_list_upcoming_preventive_maintenance_response_body import (
    EntityUpcomingPreventativeMaintenancesServiceListUpcomingPreventiveMaintenanceResponseBody,
)
from ..types.entity_upcoming_preventative_maintenances_service_update_upcoming_preventive_maintenance_response_body import (
    EntityUpcomingPreventativeMaintenancesServiceUpdateUpcomingPreventiveMaintenanceResponseBody,
)
from ..types.resolve_preventive_maintenance_action_service_resolve_preventive_maintenance_response_body import (
    ResolvePreventiveMaintenanceActionServiceResolvePreventiveMaintenanceResponseBody,
)
from .raw_client import AsyncRawPreventiveMaintenanceClient, RawPreventiveMaintenanceClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PreventiveMaintenanceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPreventiveMaintenanceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPreventiveMaintenanceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPreventiveMaintenanceClient
        """
        return self._raw_client

    def resolve_preventive_maintenance(
        self,
        *,
        asset_id: typing.Optional[str] = None,
        schedule_id: typing.Optional[str] = None,
        resolved_at: typing.Optional[str] = OMIT,
        resolved_at_engine_hours: typing.Optional[int] = OMIT,
        resolved_at_odometer: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResolvePreventiveMaintenanceActionServiceResolvePreventiveMaintenanceResponseBody:
        """
        Resolves the current open preventive maintenance instance for a schedule and asset, and automatically creates the next due record based on the schedule's intervals.

         <b>Rate limit:</b> 5 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).

        To use this endpoint, select **Write Preventive Maintenance Resolve** under the Preventive Maintenance category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a>


         **Submit Feedback**: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.

        Parameters
        ----------
        asset_id : typing.Optional[str]
            Samsara ID of the asset the instance is being resolved for.

        schedule_id : typing.Optional[str]
            ID of the preventive maintenance schedule to resolve.

        resolved_at : typing.Optional[str]
            RFC3339 time when the maintenance was resolved. Defaults to the current time if not provided.

        resolved_at_engine_hours : typing.Optional[int]
            Engine hours reading at the time of resolution.

        resolved_at_odometer : typing.Optional[int]
            Odometer reading at the time of resolution. Measured in meters.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResolvePreventiveMaintenanceActionServiceResolvePreventiveMaintenanceResponseBody
            OK response.

        Examples
        --------
        from samsara import Samsara

        client = Samsara(
            token="YOUR_TOKEN",
        )
        client.preventive_maintenance.resolve_preventive_maintenance()
        """
        _response = self._raw_client.resolve_preventive_maintenance(
            asset_id=asset_id,
            schedule_id=schedule_id,
            resolved_at=resolved_at,
            resolved_at_engine_hours=resolved_at_engine_hours,
            resolved_at_odometer=resolved_at_odometer,
            request_options=request_options,
        )
        return _response.data

    def list_preventive_maintenance_schedules(
        self,
        *,
        ids: typing.Optional[str] = None,
        after: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityPreventativeMaintenanceSchedulesServiceListPreventiveMaintenanceSchedulesResponseBody:
        """
        Returns a paginated list of preventive maintenance schedules for the organization.

         <b>Rate limit:</b> 5 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).

        To use this endpoint, select **Read Preventive Maintenance Schedules** under the Preventive Maintenance category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a>


         **Submit Feedback**: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.

        Parameters
        ----------
        ids : typing.Optional[str]
            A filter on the data based on this comma-separated list of ID values.

        after : typing.Optional[str]
             If specified, this should be the endCursor value from the previous page of results. When present, this request will return the next page of results that occur immediately after the previous page of results.

        limit : typing.Optional[int]
            The limit for how many objects will be in the response. Default and max for this value is 200 objects.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityPreventativeMaintenanceSchedulesServiceListPreventiveMaintenanceSchedulesResponseBody
            OK response.

        Examples
        --------
        from samsara import Samsara

        client = Samsara(
            token="YOUR_TOKEN",
        )
        client.preventive_maintenance.list_preventive_maintenance_schedules(
            ids="281474976710656",
        )
        """
        _response = self._raw_client.list_preventive_maintenance_schedules(
            ids=ids, after=after, limit=limit, request_options=request_options
        )
        return _response.data

    def list_upcoming_preventive_maintenance(
        self,
        *,
        schedule_ids: typing.Optional[str] = None,
        asset_ids: typing.Optional[str] = None,
        after: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityUpcomingPreventativeMaintenancesServiceListUpcomingPreventiveMaintenanceResponseBody:
        """
        Returns a paginated list of upcoming preventive maintenance schedules for the organization's assets, enriched with live telemetry (current odometer, engine hours) and due-date projections.

         <b>Rate limit:</b> 5 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).

        To use this endpoint, select **Read Upcoming Preventive Maintenance** under the Preventive Maintenance category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a>


         **Submit Feedback**: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.

        Parameters
        ----------
        schedule_ids : typing.Optional[str]
            A filter on the data based on this comma-separated list of Preventive maintenance schedule ID values.

        asset_ids : typing.Optional[str]
            A filter on the data based on this comma-separated list of Asset ID values.

        after : typing.Optional[str]
             If specified, this should be the endCursor value from the previous page of results. When present, this request will return the next page of results that occur immediately after the previous page of results.

        limit : typing.Optional[int]
            The limit for how many objects will be in the response. Default and max for this value is 200 objects.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityUpcomingPreventativeMaintenancesServiceListUpcomingPreventiveMaintenanceResponseBody
            OK response.

        Examples
        --------
        from samsara import Samsara

        client = Samsara(
            token="YOUR_TOKEN",
        )
        client.preventive_maintenance.list_upcoming_preventive_maintenance()
        """
        _response = self._raw_client.list_upcoming_preventive_maintenance(
            schedule_ids=schedule_ids, asset_ids=asset_ids, after=after, limit=limit, request_options=request_options
        )
        return _response.data

    def update_upcoming_preventive_maintenance(
        self,
        *,
        asset_id: typing.Optional[str] = None,
        schedule_id: typing.Optional[str] = None,
        last_resolved_at: typing.Optional[str] = OMIT,
        last_resolved_at_engine_hours: typing.Optional[int] = OMIT,
        last_resolved_at_odometer: typing.Optional[int] = OMIT,
        next_engine_hours: typing.Optional[int] = OMIT,
        next_odometer: typing.Optional[int] = OMIT,
        next_time: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityUpcomingPreventativeMaintenancesServiceUpdateUpcomingPreventiveMaintenanceResponseBody:
        """
        Patches the due-target and last-resolved values on the open preventive maintenance instance for a schedule and asset. Only fields provided in the request are updated.

         <b>Rate limit:</b> 5 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).

        To use this endpoint, select **Write Upcoming Preventive Maintenance** under the Preventive Maintenance category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a>


         **Submit Feedback**: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.

        Parameters
        ----------
        asset_id : typing.Optional[str]
            Samsara ID for the asset.

        schedule_id : typing.Optional[str]
            ID of the preventive maintenance schedule that the vehicle is scheduled to be serviced for.

        last_resolved_at : typing.Optional[str]
            Date and time when the prior instance was resolved.

        last_resolved_at_engine_hours : typing.Optional[int]
            Engine hours at the time the prior instance was resolved.

        last_resolved_at_odometer : typing.Optional[int]
            Odometer reading at the time the prior instance was resolved. Measured in meters.

        next_engine_hours : typing.Optional[int]
            The next engine hour value that the vehicle is scheduled to be serviced.

        next_odometer : typing.Optional[int]
            The next odometer value that the vehicle is scheduled to be serviced. Measured in meters.

        next_time : typing.Optional[str]
            The next time that the vehicle is scheduled to be serviced for a date based PM.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityUpcomingPreventativeMaintenancesServiceUpdateUpcomingPreventiveMaintenanceResponseBody
            OK response.

        Examples
        --------
        from samsara import Samsara

        client = Samsara(
            token="YOUR_TOKEN",
        )
        client.preventive_maintenance.update_upcoming_preventive_maintenance()
        """
        _response = self._raw_client.update_upcoming_preventive_maintenance(
            asset_id=asset_id,
            schedule_id=schedule_id,
            last_resolved_at=last_resolved_at,
            last_resolved_at_engine_hours=last_resolved_at_engine_hours,
            last_resolved_at_odometer=last_resolved_at_odometer,
            next_engine_hours=next_engine_hours,
            next_odometer=next_odometer,
            next_time=next_time,
            request_options=request_options,
        )
        return _response.data


class AsyncPreventiveMaintenanceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPreventiveMaintenanceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPreventiveMaintenanceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPreventiveMaintenanceClient
        """
        return self._raw_client

    async def resolve_preventive_maintenance(
        self,
        *,
        asset_id: typing.Optional[str] = None,
        schedule_id: typing.Optional[str] = None,
        resolved_at: typing.Optional[str] = OMIT,
        resolved_at_engine_hours: typing.Optional[int] = OMIT,
        resolved_at_odometer: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResolvePreventiveMaintenanceActionServiceResolvePreventiveMaintenanceResponseBody:
        """
        Resolves the current open preventive maintenance instance for a schedule and asset, and automatically creates the next due record based on the schedule's intervals.

         <b>Rate limit:</b> 5 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).

        To use this endpoint, select **Write Preventive Maintenance Resolve** under the Preventive Maintenance category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a>


         **Submit Feedback**: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.

        Parameters
        ----------
        asset_id : typing.Optional[str]
            Samsara ID of the asset the instance is being resolved for.

        schedule_id : typing.Optional[str]
            ID of the preventive maintenance schedule to resolve.

        resolved_at : typing.Optional[str]
            RFC3339 time when the maintenance was resolved. Defaults to the current time if not provided.

        resolved_at_engine_hours : typing.Optional[int]
            Engine hours reading at the time of resolution.

        resolved_at_odometer : typing.Optional[int]
            Odometer reading at the time of resolution. Measured in meters.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResolvePreventiveMaintenanceActionServiceResolvePreventiveMaintenanceResponseBody
            OK response.

        Examples
        --------
        import asyncio

        from samsara import AsyncSamsara

        client = AsyncSamsara(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.preventive_maintenance.resolve_preventive_maintenance()


        asyncio.run(main())
        """
        _response = await self._raw_client.resolve_preventive_maintenance(
            asset_id=asset_id,
            schedule_id=schedule_id,
            resolved_at=resolved_at,
            resolved_at_engine_hours=resolved_at_engine_hours,
            resolved_at_odometer=resolved_at_odometer,
            request_options=request_options,
        )
        return _response.data

    async def list_preventive_maintenance_schedules(
        self,
        *,
        ids: typing.Optional[str] = None,
        after: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityPreventativeMaintenanceSchedulesServiceListPreventiveMaintenanceSchedulesResponseBody:
        """
        Returns a paginated list of preventive maintenance schedules for the organization.

         <b>Rate limit:</b> 5 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).

        To use this endpoint, select **Read Preventive Maintenance Schedules** under the Preventive Maintenance category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a>


         **Submit Feedback**: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.

        Parameters
        ----------
        ids : typing.Optional[str]
            A filter on the data based on this comma-separated list of ID values.

        after : typing.Optional[str]
             If specified, this should be the endCursor value from the previous page of results. When present, this request will return the next page of results that occur immediately after the previous page of results.

        limit : typing.Optional[int]
            The limit for how many objects will be in the response. Default and max for this value is 200 objects.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityPreventativeMaintenanceSchedulesServiceListPreventiveMaintenanceSchedulesResponseBody
            OK response.

        Examples
        --------
        import asyncio

        from samsara import AsyncSamsara

        client = AsyncSamsara(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.preventive_maintenance.list_preventive_maintenance_schedules(
                ids="281474976710656",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_preventive_maintenance_schedules(
            ids=ids, after=after, limit=limit, request_options=request_options
        )
        return _response.data

    async def list_upcoming_preventive_maintenance(
        self,
        *,
        schedule_ids: typing.Optional[str] = None,
        asset_ids: typing.Optional[str] = None,
        after: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityUpcomingPreventativeMaintenancesServiceListUpcomingPreventiveMaintenanceResponseBody:
        """
        Returns a paginated list of upcoming preventive maintenance schedules for the organization's assets, enriched with live telemetry (current odometer, engine hours) and due-date projections.

         <b>Rate limit:</b> 5 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).

        To use this endpoint, select **Read Upcoming Preventive Maintenance** under the Preventive Maintenance category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a>


         **Submit Feedback**: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.

        Parameters
        ----------
        schedule_ids : typing.Optional[str]
            A filter on the data based on this comma-separated list of Preventive maintenance schedule ID values.

        asset_ids : typing.Optional[str]
            A filter on the data based on this comma-separated list of Asset ID values.

        after : typing.Optional[str]
             If specified, this should be the endCursor value from the previous page of results. When present, this request will return the next page of results that occur immediately after the previous page of results.

        limit : typing.Optional[int]
            The limit for how many objects will be in the response. Default and max for this value is 200 objects.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityUpcomingPreventativeMaintenancesServiceListUpcomingPreventiveMaintenanceResponseBody
            OK response.

        Examples
        --------
        import asyncio

        from samsara import AsyncSamsara

        client = AsyncSamsara(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.preventive_maintenance.list_upcoming_preventive_maintenance()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_upcoming_preventive_maintenance(
            schedule_ids=schedule_ids, asset_ids=asset_ids, after=after, limit=limit, request_options=request_options
        )
        return _response.data

    async def update_upcoming_preventive_maintenance(
        self,
        *,
        asset_id: typing.Optional[str] = None,
        schedule_id: typing.Optional[str] = None,
        last_resolved_at: typing.Optional[str] = OMIT,
        last_resolved_at_engine_hours: typing.Optional[int] = OMIT,
        last_resolved_at_odometer: typing.Optional[int] = OMIT,
        next_engine_hours: typing.Optional[int] = OMIT,
        next_odometer: typing.Optional[int] = OMIT,
        next_time: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityUpcomingPreventativeMaintenancesServiceUpdateUpcomingPreventiveMaintenanceResponseBody:
        """
        Patches the due-target and last-resolved values on the open preventive maintenance instance for a schedule and asset. Only fields provided in the request are updated.

         <b>Rate limit:</b> 5 requests/sec (learn more about rate limits <a href="https://developers.samsara.com/docs/rate-limits" target="_blank">here</a>).

        To use this endpoint, select **Write Upcoming Preventive Maintenance** under the Preventive Maintenance category when creating or editing an API token. <a href="https://developers.samsara.com/docs/authentication#scopes-for-api-tokens" target="_blank">Learn More.</a>


         **Submit Feedback**: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.

        Parameters
        ----------
        asset_id : typing.Optional[str]
            Samsara ID for the asset.

        schedule_id : typing.Optional[str]
            ID of the preventive maintenance schedule that the vehicle is scheduled to be serviced for.

        last_resolved_at : typing.Optional[str]
            Date and time when the prior instance was resolved.

        last_resolved_at_engine_hours : typing.Optional[int]
            Engine hours at the time the prior instance was resolved.

        last_resolved_at_odometer : typing.Optional[int]
            Odometer reading at the time the prior instance was resolved. Measured in meters.

        next_engine_hours : typing.Optional[int]
            The next engine hour value that the vehicle is scheduled to be serviced.

        next_odometer : typing.Optional[int]
            The next odometer value that the vehicle is scheduled to be serviced. Measured in meters.

        next_time : typing.Optional[str]
            The next time that the vehicle is scheduled to be serviced for a date based PM.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityUpcomingPreventativeMaintenancesServiceUpdateUpcomingPreventiveMaintenanceResponseBody
            OK response.

        Examples
        --------
        import asyncio

        from samsara import AsyncSamsara

        client = AsyncSamsara(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.preventive_maintenance.update_upcoming_preventive_maintenance()


        asyncio.run(main())
        """
        _response = await self._raw_client.update_upcoming_preventive_maintenance(
            asset_id=asset_id,
            schedule_id=schedule_id,
            last_resolved_at=last_resolved_at,
            last_resolved_at_engine_hours=last_resolved_at_engine_hours,
            last_resolved_at_odometer=last_resolved_at_odometer,
            next_engine_hours=next_engine_hours,
            next_odometer=next_odometer,
            next_time=next_time,
            request_options=request_options,
        )
        return _response.data
